name: changelog

on:
  push:
    branches:
      - main
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run git-cliff
        uses: tj-actions/git-cliff@v1
        output: CHANGELOG.md
